"""Build a validated troubleshooting plan from a query and SIIS knowledge text.

Every step comes from the SIIS text; every deeplink comes verbatim from the
catalog (or is the documented placeholder). Nothing is generated by a model.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass
import re
from typing import Any

from app.services.action_ordering import ordered_values
from app.services.key_matcher import DUMMY_URI, KeyIndex, tap_targets
from app.services.plan_validator import validate_plan
from app.services.relevance import relevance
from app.services.siis_parser import Section, embedded_title, is_imperative, parse_sections
from app.services.variations import generate_variations

_WORD = re.compile(r"[A-Za-z0-9]+(?:['-][A-Za-z0-9]+)*")
_SPLIT_NAME = re.compile(r"\s+(?:and|&)\s+|\s*/\s*")
_CRITICAL = re.compile(
    r"\b(?:factory\s+(?:data\s+)?reset|safe\s+mode|restart|reboot|clear\s+data|firmware|"
    r"recovery\s+mode|wipe|erase)\b",
    re.IGNORECASE,
)
_SETTINGS = re.compile(r"(?<!Quick )\bSettings\b")
_STOPWORDS = frozenset("a an the your my to of on for with in and or is are".split())
_TOPIC_STOP = _STOPWORDS | frozenset(
    "some things check first how use you can cannot samsung galaxy phone tablet".split()
)
_TOPIC_CUT = re.compile(r"\s+(?:on|when|in|for|if|not|does|do|is|are)\s+|\(")
_VALIDATION_FIELDS = ("deeplink", "key", "resultType", "condition", "value")


@dataclass(frozen=True)
class PlanBuild:
    """Outcome of one build: the response body, its paraphrases, and any rule errors."""

    response: dict[str, Any]
    query_variations: list[str]
    relevance: float
    errors: tuple[str, ...]


def _words(text: str) -> list[str]:
    return _WORD.findall(text)


def _cap(word: str) -> str:
    return word[:1].upper() + word[1:]


def _base(heading: str, steps: list[str]) -> str:
    return _SPLIT_NAME.split(heading)[0].strip() or " ".join(steps[0].split()[:4])


def _topic(title: str) -> str:
    head = _TOPIC_CUT.split(title)[0]
    words = [w for w in _words(head) if w.lower() not in _TOPIC_STOP][:3]
    return " ".join(_cap(w) for w in words) or "Device Issue"


def _title(topic: str) -> str:
    words = topic.split()
    if len(words) < 2:
        words.append("troubleshooting")
    return " ".join([_cap(words[0].lower()), *(w.lower() for w in words[1:])])


def _action_name(heading: str, steps: list[str]) -> str:
    return " ".join(_cap(w) for w in _words(_base(heading, steps))[:6]) or "Troubleshooting Step"


def _describe(heading: str, steps: list[str]) -> str:
    base = _base(heading, steps)
    core = [w.lower() for w in _words(base) if w.lower() not in _STOPWORDS][:3]
    lead = "It will help you" if is_imperative(base) else "It will help with"
    return f"{lead} " + " ".join(core or ["complete", "this", "step"])


def _catalog_link(entry: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "deeplink": entry["deeplink"],
        "description": entry["description"],
        "message": entry.get("message") or "",
        "originalType": entry.get("originalType"),
    }


def _validation_link(entry: Mapping[str, Any]) -> dict[str, Any] | None:
    validation = entry.get("validation")
    if not isinstance(validation, Mapping) or not validation.get("deeplink") or not validation.get("key"):
        return None
    return {field: validation[field] for field in _VALIDATION_FIELDS if field in validation}


def _placeholder_link(label: str) -> dict[str, Any]:
    return {
        "deeplink": DUMMY_URI,
        "description": f"Opens the {label} Settings screen",
        "message": f"Open the {label} screen in Settings",
        "originalType": "placeholder",
    }


def _build_action(section: Section, index: KeyIndex) -> dict[str, Any] | None:
    """Build one action, resolving its deeplink before deciding whether it is critical.

    The catalog only ever models View/Toggle/Update-value actions (confirmed: it has no
    entry for an immediate one-tap destructive action like a live factory reset or restart).
    So whenever a step group resolves to a real catalog entry, that action is, by
    construction, a safe Settings screen -- even when the catalog's own setting name
    contains a word the critical-keyword scan would otherwise flag, such as the toggle
    "Restart the device when needed" or the view-only "Restart on schedule". Checking the
    catalog match first, and only falling back to the keyword scan when there is none,
    keeps genuinely disruptive, physical-button instructions (which never resolve to a
    catalog entry) critical exactly as before.
    """
    steps = list(section.steps)
    if not steps:
        return None
    choice = index.find(steps, section.body)
    critical = choice is None and bool(_CRITICAL.search(" ".join([section.heading, *steps])))
    group: dict[str, Any] = {"steps": steps, "actionableDeeplink": None, "validationDeeplink": None}
    if critical:
        category = "critical"
    elif choice is not None or any(_SETTINGS.search(step) for step in steps):
        category = "auto"
        if choice is not None:
            group["actionableDeeplink"] = _catalog_link(choice.entry)
            group["validationDeeplink"] = _validation_link(choice.entry)
        else:
            label = " ".join(next(iter(reversed(tap_targets(steps))), "relevant").split()[:2])
            group["actionableDeeplink"] = _placeholder_link(label)
    else:
        category = "manual"
    return {
        "actionName": _action_name(section.heading, steps),
        "description": _describe(section.heading, steps),
        "stepGroups": [group],
        "category": category,
    }


def _merge_same_screen(actions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Fold adjacent actions that open the same screen into one action."""
    merged: list[dict[str, Any]] = []
    for action in actions:
        link = action["stepGroups"][0]["actionableDeeplink"]
        previous = merged[-1]["stepGroups"][-1]["actionableDeeplink"] if merged else None
        same = (
            link is not None
            and previous is not None
            and (link["deeplink"], link["message"]) == (previous["deeplink"], previous["message"])
        )
        if same:
            merged[-1]["stepGroups"].extend(action["stepGroups"])
        else:
            merged.append(action)
    return merged


class PlanBuilder:
    """Turn (query, SIIS text) into a validated plan or refuse."""

    def __init__(self, catalog: Iterable[Mapping[str, Any]]) -> None:
        self.catalog = list(catalog)
        self._index = KeyIndex(self.catalog)

    def build(self, query: str, content: str, title: str = "") -> PlanBuild | None:
        """Return a plan, or ``None`` when the text has no usable, relevant steps.

        ``title`` defaults to "" for callers with no separate title field (the public
        troubleshoot() API has none). In that case the article's own embedded title is
        recovered from its "<categories> <Title> ( <categories>): " prefix when present,
        so a cold siis_response is not silently reduced to a generic "Device Issue" topic
        or a redundant one derived from its first heading alone.
        """
        title = title or embedded_title(content) or ""
        sections = parse_sections(content, title)
        article = " ".join(f"{s.heading} {s.body}" for s in sections)
        score = relevance(query, article, title)
        if score <= 0.0:
            return None
        actions = [a for s in sections if (a := _build_action(s, self._index)) is not None]
        if not actions:
            return None
        topic = _topic(title or sections[0].heading)
        response = {
            "contexts": [
                {
                    "goal": f"Follow these steps to perform this {topic} Troubleshooting",
                    "title": _title(topic),
                    "score": round(min(1.0, 0.5 + score), 2),
                    "actions": ordered_values(_merge_same_screen(actions)),
                }
            ]
        }
        variations = generate_variations(query, topic)
        result = validate_plan({**response, "query_variations": variations}, self.catalog)
        return PlanBuild(response, variations, score, result.errors)
